Repository insolar/assured-ledger, pull requests merged in 2020-07, with the labels that each got.

#424 PLAT-522, PLAT-521, PLAT-586: add test for double pulse change
  ledger-core/testutils/predicate/predicate.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
Labels: WIP

#482 PLAT-636: test changes
  ledger-core/doc.go
Labels: ready to merge

#486 PLAT-636: invalidate reviews on push
  .github/policy.yml
Labels: autoupdate, ready to merge

#487 PLAT-644: even if we can not copy logger, we can re-use output
  ledger-core/log/builder.go
Labels: ready to merge

#490 PLAT-636: stricter merge rules
  .github/PULL_REQUEST_TEMPLATE.md
  .github/bulldozer.yml
  .github/mergeable.yml
  .github/policy.yml
Labels: automerge, autoupdate, ready to merge

#491 NOISSUE: use object reference as publishing key for object's shared data
  ledger-core/virtual/object/catalog.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
  ledger-core/virtual/object/object_publish_callsummary_test.go
  ledger-core/virtual/object/object_test.go
Labels: automerge, autoupdate

#467 PLAT-515: add method happy path test
  ledger-core/conveyor/conveyor_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/virtual.go
Labels: automerge, autoupdate

#494 PLAT-526: method will stop if obj state is Missing
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#492 NOISSUE: benchmark GetBalance on TestWallet contract
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/testutils/utils.go
Labels: automerge, autoupdate, ready to merge

#496 NOISSUE: method will stop if object state is Missing
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#498 PLAT-638: and PLAT-646 fix flacky tests
  ledger-core/virtual/integration/mock/typepublishchecker.go
  ledger-core/virtual/integration/outgoing_test.go
Labels: automerge, autoupdate

#497 NOISSUE: Architectural supervision fixes
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object.plantuml
Labels: automerge

#501 NOISSUE: Perf test for SlotMachine
  ledger-core/conveyor/smachine/perf/perf_test.go
  ledger-core/conveyor/smachine/slot_machine_execute.go
Labels: automerge, autoupdate

#493 PLAT-516: parallel call of two ordered methods
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#500 PLAT-651: use map[pulse]counter to speed up calculation of earliest pulse
  ledger-core/virtual/callregistry/request_table.go
  ledger-core/virtual/callregistry/request_table_test.go
  ledger-core/virtual/callregistry/working_table.go
Labels: automerge, autoupdate

#502 NOISSUE: more benchmarks that involve our Test API
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#510 PLAT-412: add wallet/delete api
  ledger-core/application/functest/api_test_utils.go
  ledger-core/application/testwalletapi/README.md
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/application/testwalletapi/testwalletserver.go
  ledger-core/load/util/api_test_utils.go
Labels: automerge, autoupdate

#468 PLAT-367: get rid of IgnoreAllErrors from most of the tests
  ledger-core/application/api/availability_test.go
  ledger-core/application/api/seed_test.go
  ledger-core/network/hostnetwork/hostnetwork_test.go
  ledger-core/network/integration/suite_test.go
  ledger-core/network/servicenetwork/servicenetwork_test.go
  ledger-core/server/internal/headless/components_test.go
  ledger-core/server/internal/virtual/components_test.go
  ledger-core/virtual/integration/delegated_finished_test.go
Labels: automerge, autoupdate

#512 NOISSUE: remove unnecessary Sprintf
  ledger-core/application/testwalletapi/handlers.go
Labels: automerge, autoupdate

#513 NOISSUE: remove load
  ledger-core/go.mod
  ledger-core/load/README.md
  ledger-core/load/attackers.go
  ledger-core/load/checks.go
  ledger-core/load/cmd/load/main.go
  ledger-core/load/create_contract_test_attack.go
  ledger-core/load/gen_cfg/generator_assured_ledger.yaml
  ledger-core/load/gen_cfg/generator_assured_ledger_whoami.yaml
  ledger-core/load/gen_cfg/generator_local.yaml
  ledger-core/load/get_contract_test_attack.go
  ledger-core/load/get_contract_test_debug_attack.go
  ledger-core/load/labels.go
  ledger-core/load/run_configs/all_sequence.yaml
  ledger-core/load/run_configs/all_sequence_debug_whoami.yaml
  ledger-core/load/run_configs/create_contract_test.yaml
  ledger-core/load/run_configs/get_contract_test.yaml
  ledger-core/load/run_configs/set_contract_test.yaml
  ledger-core/load/set_contract_test_attack.go
  ledger-core/load/util/api_test_utils.go
  ledger-core/load/util/structures.go
  ledger-core/load/util/test_utils.go
Labels: automerge

#507 PLAT-376: ignore response error
  ledger-core/network/hostnetwork/flaky_test.go
  ledger-core/network/hostnetwork/hostnetwork_test.go
Labels: automerge, autoupdate

#499 PLAT-656: automated mock generation for Typed checker of Publisher mock
  ledger-core/tools.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/mock/defaultchecker.go
  ledger-core/virtual/integration/mock/publisher/checker/common.go
  ledger-core/virtual/integration/mock/publisher/checker/default.go
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
  ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/main.go
  ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/template.go
  ledger-core/virtual/integration/mock/publisher/publisher.go
  ledger-core/virtual/integration/utils/case.go
  ledger-core/virtual/integration/utils/server.go
Labels: automerge, autoupdate

#489 PLAT-554: max outgoing rerty
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/integration/contract_calls_test.go
Labels: automerge, autoupdate

#506 PLAT-655: fix TestDelegationToken_SuccessCheckCorrectToken
  ledger-core/virtual/integration/delegationtoken_test.go
Labels: automerge, autoupdate

#515 PLAT-652: remove duplicates
  ledger-core/virtual/integration/delegated_finished_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#504 PLAT-543: check that validated state equals to last dirty satet in st…
  ledger-core/virtual/integration/statereport_test.go
Labels: automerge, autoupdate

#524 NOISSUE: log inbound message details for further analysis
  ledger-core/virtual/handlers/handle_meta.go
Labels: automerge, autoupdate

#527 NOISSUE: fix path for extended logs in master checks
  .github/workflows/master-checks.yaml
  ledger-core/.gitignore
Labels: automerge, autoupdate

#528 NOISSUE: PR body in squash commit message
  .github/bulldozer.yml
Labels: automerge, autoupdate

#525 NOISSUE: old code was setting default migration to special and never changed it
  ledger-core/virtual/handlers/vfindcallrequest.go
  ledger-core/virtual/handlers/vfindcallrequest.plantuml
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
Labels: automerge, autoupdate

#518 PLAT-415: add simple functest for wallet/delete
  ledger-core/application/functest/structures.go
  ledger-core/application/functest/wallet_delete_test.go
Labels: automerge, autoupdate

#531 PLAT-659: fixed flaky TestVirtual_CallMethodOutgoing_WithTwicePulseChange
  ledger-core/virtual/integration/outgoing_test.go
Labels: automerge, autoupdate

#530 PLAT-562: update namings
  ledger-core/virtual/integration/delegationtoken_test.go
Labels: automerge, autoupdate

#509 PLAT-430: Add conveyor limiter to control max parallel processing
  ledger-core/conveyor/conveyor.go
  ledger-core/conveyor/conveyor_semaphore.go
  ledger-core/conveyor/conveyor_semaphore_test.go
  ledger-core/conveyor/smachine/smsync/sync_sema_partial.go
  ledger-core/conveyor/smachine/smsync/sync_semaphore.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/virtual.go
Labels: automerge, autoupdate

#526 PLAT-402: Pass LatestValidatedState in VStateReport
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/object/object.go
Labels: automerge, autoupdate

#532 PLAT-582: added leackchecker to all virtual tests
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute_isolation_negotiation_test.go
  ledger-core/virtual/execute/execute_publish_callsummary_test.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/execute/migration_test.go
  ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
  ledger-core/virtual/handlers/vdelegatedcallresponse_test.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/handlers/vstaterequest_test.go
  ledger-core/virtual/integration/constructor_api_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_api_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/object_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/scenario_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/staterequest_test.go
  ledger-core/virtual/integration/vdelegated_test.go
  ledger-core/virtual/integration/vstatereport_test.go
  ledger-core/virtual/integration/watermill_integration_test.go
  ledger-core/virtual/object/finalizedstate/statefinalizer_test.go
  ledger-core/virtual/object/info_test.go
  ledger-core/virtual/object/object_migration_test.go
  ledger-core/virtual/object/object_publish_callsummary_test.go
  ledger-core/virtual/object/object_test.go
Labels: automerge, autoupdate

#529 NOISSUE: Improve prev pulse handling
  ledger-core/conveyor/pulse_slot.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/statemachine/dispatcher.go
Labels: automerge, autoupdate

#534 PLAT-660: TestVirtual_Method_CheckPendingsCount hangs
  ledger-core/testutils/runner/logicless/service.go
  ledger-core/virtual/integration/method_pulse_change_test.go
Labels: automerge, autoupdate

#537 PLAT-663: checker.Typed race fix
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
  ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/template.go
Labels: automerge, autoupdate

#535 PLAT-583: long integration runs
  .github/workflows/long-funcs.yaml
  ledger-core/Makefile.testing
  ledger-core/application/api/availability_test.go
  ledger-core/log/bpbuffer/backpressure_buffer_test.go
  ledger-core/network/integration/network_test.go
Labels: automerge, autoupdate

#536 PLAT-635: change "processing message" loglevel to INFO
  ledger-core/virtual/handlers/handle_meta.go
Labels: autoupdate

#539 NOISSUE: speedup deduplication tests
  ledger-core/virtual/integration/deduplication/constructor_test.go
Labels: automerge, autoupdate

#538 NOISSUE: fix watermill integration test races
  ledger-core/virtual/integration/watermill_integration_test.go
Labels: automerge, autoupdate

#541 PLAT-583: fixup tags and GA names
  .github/workflows/long-funcs.yaml
  ledger-core/application/api/availability_test.go
  ledger-core/network/integration/network_test.go
Labels: automerge, autoupdate

#503 PLAT-647: A.New with twice pulse change in ExecutionStart
  ledger-core/virtual/integration/constructor_test.go
Labels: automerge, autoupdate

#511 PLAT-584: SMVFindCallRequestAwaitSMCallSummary test
  ledger-core/virtual/handlers/vfindcallrequest_test.go
Labels: automerge, autoupdate

#545 NOISSUE: add `prefix_tree_slow_test.go` tests to longtests
  .github/mergeable.yml
  .github/workflows/long-funcs.yaml
  ledger-core/Makefile.testing
  ledger-core/ledger/jet/prefix_tree_slow_test.go
Labels: automerge, autoupdate

#550 HOTFIX: remove disapproval rule
  .github/policy.yml
Labels: automerge, autoupdate

#533 PLAT-431: Inherit SMObject semaphores from global limiter
  ledger-core/conveyor/conveyor_semaphore.go
  ledger-core/conveyor/conveyor_semaphore_test.go
  ledger-core/server/internal/virtual/components.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vfindcallrequest_test.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
  ledger-core/virtual/object/object_publish_callsummary_test.go
  ledger-core/virtual/object/object_test.go
Labels: automerge, autoupdate

#549 PLAT-584: SMVFindCallRequest test
  ledger-core/virtual/handlers/vfindcallrequest_test.go
Labels: automerge, autoupdate

#553 NOISSUE: move runner limiter to virtual/tool pkg
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
  ledger-core/virtual/object/object_publish_callsummary_test.go
  ledger-core/virtual/object/object_test.go
  ledger-core/virtual/tool/runnerlimiter.go
  ledger-core/virtual/tool/runnerlimiter_test.go
  ledger-core/virtual/virtual.go
Labels: automerge, autoupdate

#522 PLAT-375: test no dead lock on semaphore
  ledger-core/virtual/integration/contract_calls_test.go
Labels: automerge, autoupdate

#556 PLAT-666: Fixed vfindcallrequest test
  ledger-core/virtual/handlers/vfindcallrequest_test.go
Labels: automerge, autoupdate

#542 NOISSUE: setup cache for go mod based on go.sum
  .github/workflows/consensus-checks.yaml
  .github/workflows/linux-checks.yaml
  .github/workflows/long-funcs.yaml
  .github/workflows/master-checks.yaml
  .github/workflows/ve-performance-checks.yaml
  .github/workflows/windows-checks.yaml
  ledger-core/.dockerignore
  ledger-core/.gitignore
  ledger-core/Dockerfile
  ledger-core/Makefile
  ledger-core/Makefile.testing
  ledger-core/go.mod
  ledger-core/go.sum
  ledger-core/tools.go
Labels: autoupdate

#557 NOISSUE: gocenter instead of goproxy
  .github/workflows/consensus-checks.yaml
  .github/workflows/linux-checks.yaml
  .github/workflows/master-checks.yaml
  .github/workflows/ve-performance-checks.yaml
Labels: automerge, autoupdate

#546 PLAT-403: store validated state descriptor
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
Labels: automerge, autoupdate

#548 PLAT-414: call self.Destroy from TestWallet
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/runner/adapter.go
  ledger-core/runner/executor/common/rpctypes/rpctypes.go
  ledger-core/runner/runner_rpc.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/method_api_test.go
  ledger-core/virtual/integration/utils/server_http.go
Labels: automerge, autoupdate

#551 NOISSUE: LogCase method for TestRail marks
  ledger-core/application/api/requester/requester_test.go
  ledger-core/instrumentation/inslogger/instestlogger/test_case.go
  ledger-core/instrumentation/inslogger/instestlogger/test_helper.go
  ledger-core/virtual/integration/vdelegated_test.go
Labels: autoupdate

#559 PLAT-404: use validated state
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/application/testwalletapi/testwalletserver.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/object/object.go
Labels: automerge, autoupdate

#566 NOISSUE: delete Parent from object, we don't use it
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/runner/runner.go
  ledger-core/runner/runner_test.go
  ledger-core/virtual/descriptor/object.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/object/finalizedstate/statefinalizer_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
Labels: automerge, autoupdate

#565 PLAT-669: long integration workflow fix
  .github/workflows/long-integration.yaml
Labels: automerge, autoupdate

#555 PLAT-432: release semaphore for outgoing
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/migration_test.go
  ledger-core/virtual/integration/contract_calls_test.go
Labels: automerge, autoupdate

#540 PLAT-433: parallel call check semaphore
  ledger-core/virtual/integration/semaphore_test.go
Labels: automerge, autoupdate

#564 PLAT-407: forbid tolerable + validated isolation
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#543 PLAT-559: sender test
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/sender_test.go
Labels: autoupdate

#569 PLAT-406: VCallRequest fail with error if interference==intolerable and runner change state
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#568 PLAT-671: send VDelegatedRequestFinished after retries for correct pending count
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/integration/contract_calls_test.go
Labels: automerge, autoupdate

#573 NOISSUE: fix_ci_runs_on_wrong_commit
  .github/workflows/linux-checks.yaml
  .github/workflows/windows-checks.yaml
Labels: automerge, autoupdate

#576 NOISSUE: fix retry test race
  ledger-core/virtual/integration/contract_calls_test.go
Labels: automerge, autoupdate

#574 PLAT-409: fail if intolerable call with validated state and object have no such state
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_isolation_negotiation_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#567 PLAT-544: simple deactivate object test
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#581 NOISSUE: past eclipsed by present under constant load
  ledger-core/conveyor/sm_pulse_slot.go
  ledger-core/conveyor/sm_pulse_slot.plantuml
Labels: automerge, autoupdate

#583 PLAT-592: bugfix flaky TestHostNetwork_WrongHandler
  ledger-core/network/hostnetwork/hostnetwork_test.go
Labels: automerge, autoupdate

#547 PLAT-643: Validate VStateReport
  ledger-core/insolar/payload/validation.go
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/semaphore_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/staterequest_test.go
  ledger-core/virtual/integration/vdelegated_test.go
Labels: automerge, autoupdate

#582 PLAT-524: check that requests with logic error not become pending requests
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/utils/assert_jump.go
Labels: automerge, autoupdate

#584 NOISSUE: Improved dep injector
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/conveyor/conveyor_test.go
  ledger-core/conveyor/main/conveyor_test_main.go
  ledger-core/conveyor/sm_antique_test.go
  ledger-core/conveyor/smachine/api_state_machine.go
  ledger-core/conveyor/smachine/example/player.go
  ledger-core/conveyor/smachine/main/example/example_1.go
  ledger-core/conveyor/smachine/main/example/sm_vm_object.go
  ledger-core/conveyor/smachine/slot_machine.go
  ledger-core/ledger/server/datawriter/smdrop.go
  ledger-core/ledger/server/datawriter/smline.go
  ledger-core/ledger/server/datawriter/smplash.go
  ledger-core/ledger/server/requests/smregister.go
  ledger-core/vanilla/injector/api_inject.go
  ledger-core/vanilla/injector/container.go
  ledger-core/vanilla/injector/injector.go
  ledger-core/vanilla/injector/lazy_name.go
  ledger-core/vanilla/injector/resolver.go
  ledger-core/virtual/callsummary/callsummary.go
  ledger-core/virtual/execute/delegatedtokenrequest.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/handlers/vcallrequest.go
  ledger-core/virtual/handlers/vcallresult.go
  ledger-core/virtual/handlers/vdelegatedcallrequest.go
  ledger-core/virtual/handlers/vdelegatedcallresponse.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/handlers/vfindcallrequest.go
  ledger-core/virtual/handlers/vfindcallresponse.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/handlers/vstaterequest.go
  ledger-core/virtual/object/finalizedstate/statefinalizer.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/tool/runnerlimiter_test.go
Labels: automerge, autoupdate

#587 PLAT-700: refactor tests 4974, 5106, 5321
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#521 NOISSUE: remove ve-performance CI
  .github/workflows/ve-performance-checks.yaml
Labels: automerge, autoupdate

#572 NOISSUE: remove bad build tags from launchnet.sh
  ledger-core/Makefile.build
  ledger-core/README.md
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/scripts/insolard/launchnet.sh
Labels: automerge, autoupdate

#588 HOTFIX: fix improper NSH stub
  ledger-core/conveyor/sm_pulse_slot.go
  ledger-core/network/consensus/adapters/upstream.go
Labels: automerge

#589 PLAT-653: revert use synckit.Backoff
  ledger-core/network/gateway/base.go
  ledger-core/network/gateway/bootstrap/requester.go
  ledger-core/network/gateway/discovery_bootstrap.go
  ledger-core/network/gateway/joiner_bootstrap.go
  ledger-core/network/gateway/joiner_bootstrap_test.go
  ledger-core/network/gateway/nonetwork.go
  ledger-core/network/gateway/nonetwork_test.go
Labels: automerge, autoupdate

#577 PLAT-676: Improve correlation between init and migrate
  ledger-core/conveyor/smachine/slot_machine_test.go
  ledger-core/conveyor/smachine/slot_prepare.go
Labels: automerge, autoupdate

#590 NOISSUE: alternative testrail output hotfix (#563)
  ledger-core/Makefile.testing
Labels: automerge, autoupdate

#580 PLAT-677: VStateRequest [RequestLatestValidatedState] test
  ledger-core/virtual/integration/staterequest_test.go
Labels: automerge, autoupdate

#591 PLAT-697: fix managing of pending counters
  ledger-core/virtual/callregistry/working_table_test.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
Labels: automerge, autoupdate

#592 PLAT-416: object deactivation
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/insolar/payload/validation.go
  ledger-core/runner/bench_test.go
  ledger-core/runner/requestresult/requestresult.go
  ledger-core/runner/runner_test.go
  ledger-core/virtual/descriptor/object.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_isolation_negotiation_test.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_api_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/object/finalizedstate/statefinalizer_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
Labels: automerge, autoupdate

#600 NOISSUE: configurable, less hardcoded launchnet.sh
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/scripts/generate_insolar_configs.go
  ledger-core/scripts/insolard/bootstrap_template.yaml
  ledger-core/scripts/insolard/launchnet.sh
Labels: autoupdate

#601 PLAT-696: better VStateReport validation
  ledger-core/insolar/payload/validation.go
  ledger-core/insolar/payload/validation_vstatereport.go
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate
