Repository insolar/assured-ledger, pull requests merged in 2020-08, with the labels that each got.

#598 PLAT-687: Validate VFindCallRequest fields
  ledger-core/insolar/payload/validattion_vfindcallrequest.go
  ledger-core/virtual/integration/sender_test.go
Labels: automerge, autoupdate

#594 NOISSUE: fix unstable test
  ledger-core/virtual/integration/staterequest_test.go
Labels: automerge, autoupdate

#586 PLAT-396: return error when we try to call method on inactive object
  ledger-core/testutils/runner/adapter/adapter.go
  ledger-core/virtual/callregistry/working_table.go
  ledger-core/virtual/descriptor/object.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/object/object.go
Labels: automerge, autoupdate

#602 PLAT-678: test VStateRequest on the deactivated object
  ledger-core/virtual/integration/staterequest_test.go
Labels: automerge, autoupdate

#599 PLAT-679: update test with checks for validated state
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/statereport_test.go
Labels: automerge, autoupdate

#603 PLAT-686: implement VFindCallResponse validation
  ledger-core/insolar/payload/validation_vcallresult.go
  ledger-core/insolar/payload/validation_vfindcallresponse.go
  ledger-core/virtual/integration/sender_test.go
Labels: automerge, autoupdate

#606 PLAT-682: add test on deactivation with Intolerable flag
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#605 PLAT-681: test object deactivation with change pulse
  ledger-core/runner/requestresult/requestresult.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#610 NOISSUE: fix naming in test and outgoing for DelegationToken
  ledger-core/virtual/integration/delegationtoken_test.go
Labels: automerge, autoupdate

#608 PLAT-702: fix test TestVirtual_SenderCheck_With_ExpectedVE
  ledger-core/virtual/integration/sender_test.go
Labels: automerge, autoupdate

#614 NOISSUE: t.Log -> insrail.LogCase
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/staterequest_test.go
Labels: automerge, autoupdate

#613 PLAT-717: fix check UnorderedPendingCount for Inactive VStateReport
  ledger-core/insolar/payload/validation_vstatereport.go
Labels: automerge, autoupdate

#609 PLAT-592: attempt to fix TestHostNetwork_WrongHandler
  ledger-core/network/hostnetwork/hostnetwork_test.go
  ledger-core/network/transport/fake.go
Labels: automerge, autoupdate

#612 PLAT-699: NodeReadyMiddleware
  ledger-core/application/functest/api_test_utils.go
  ledger-core/application/testwalletapi/testwalletserver.go
Labels: automerge, autoupdate

#617 PLAT-709: test call after deactivation
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#616 PLAT-713: unskip test C5008: constructor deduplication on inactive state
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
Labels: automerge, autoupdate

#615 PLAT-706: update happy-path test and fix small bug
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/object/object.go
Labels: automerge, autoupdate

#620 NOISSUE: proper VirtualExecutorForObject
  ledger-core/appctl/affinity/affinity.go
Labels: automerge, autoupdate

#621 PLAT-661: application/api tests timeout
  ledger-core/application/api/availability.go
  ledger-core/application/api/availability_test.go
Labels: automerge, autoupdate

#622 PLAT-716: deduplicate previous pulse call even object is deactivated in current pulse
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#618 PLAT-708: test finish partial object deactivation
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#623 PLAT-707: test deduplicate deactivation
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#624 PLAT-721: wait for all AsyncCalls
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#607 PLAT-688: implement VDelegatedRequestFinshed validation
  ledger-core/insolar/contract/virtual.go
  ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
  ledger-core/insolar/payload/vcallflags.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#611 PLAT-690: implementinig VDelegatedCallRequest checks
  ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
  ledger-core/insolar/payload/validation_vfindcallrequest.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/vdelegated_test.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#625 NOISSUE: rename SMStateFinalizer to SMPreservedStateReport
  ledger-core/virtual/handlers/vstaterequest.go
  ledger-core/virtual/handlers/vstaterequest_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/object_migration_test.go
  ledger-core/virtual/object/object_publish_callsummary_test.go
  ledger-core/virtual/object/preservedstatereport/preservedstatereport.go
  ledger-core/virtual/object/preservedstatereport/preservedstatereport.plantuml
  ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go
  ledger-core/virtual/object/preservedstatereport/storage.go
Labels: automerge, autoupdate

#627 PLAT-715: delete duplicate 5184 and 5123
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#628 PLAT-703: delete duplicate 5436 and refactor 4959
  ledger-core/virtual/integration/contract_calls_test.go
Labels: automerge, autoupdate

#631 PLAT-714: delete test 5012
  ledger-core/virtual/integration/deduplication/constructor_test.go
Labels: automerge, autoupdate

#629 PLAT-704: update case 5089
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#632 PLAT-689: implentation of VDelegatedCallResponse checks
  ledger-core/insolar/payload/validate_vdelegatedcallresponse.go
  ledger-core/insolar/payload/validation.go
  ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#633 PLAT-691: implement VStateRequest validation
  ledger-core/insolar/payload/requestedcontent.go
  ledger-core/insolar/payload/requestedcontent_test.go
  ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
  ledger-core/insolar/payload/validation_vstaterequest.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/staterequest_test.go
Labels: automerge, autoupdate

#635 NOISSUE: reduce allocations on conveyor log
  ledger-core/instrumentation/insconveyor/logger_step.go
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#636 NOISSUE: conveyor tunings
  ledger-core/conveyor/smachine/api_worker.go
  ledger-core/conveyor/smachine/context_machine.go
  ledger-core/conveyor/smachine/context_worker_wrapper.go
  ledger-core/conveyor/smachine/slot_bargein.go
  ledger-core/conveyor/smachine/slot_machine.go
  ledger-core/conveyor/smachine/slot_machine_execute.go
  ledger-core/conveyor/smachine/slot_machine_migrate.go
  ledger-core/conveyor/smachine/slot_machine_queue.go
  ledger-core/conveyor/smachine/slot_utils.go
  ledger-core/conveyor/smachine/worker_detachable.go
  ledger-core/conveyor/sworker/worker_detach.go
  ledger-core/conveyor/sworker/worker_simple.go
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#637 PLAT-701: call two Intolerable methods with Tolerable flag
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#630 PLAT-712: update deduplication tests
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deduplication_test.go
Labels: automerge, autoupdate

#638 NOISSUE: update tests
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/method_test.go
Labels: autoupdate

#639 NOISSUE: add asserts for LatestState
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/outgoing_test.go
Labels: automerge, autoupdate

#640 NOISSUE: delete 5239
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#642 PLAT-724: fix TestSMExecute_StopWithoutMessagesIfPulseChangedBeforeOutgoing
  ledger-core/virtual/execute/execute_test.go
Labels: automerge, autoupdate

#649 NOISSUE: use jsoniter in testwalletapi
  ledger-core/application/testwalletapi/handlers.go
Labels: automerge, autoupdate

#650 NOISSUE: Additional boost flag
  ledger-core/conveyor/smachine/api_context.go
  ledger-core/conveyor/smachine/api_step.go
  ledger-core/conveyor/smachine/context_basic.go
  ledger-core/conveyor/smachine/execution_context_mock.go
  ledger-core/conveyor/smachine/initialization_context_mock.go
  ledger-core/conveyor/smachine/migration_context_mock.go
  ledger-core/conveyor/smachine/slot.go
  ledger-core/conveyor/smachine/slot_machine.go
  ledger-core/conveyor/smachine/slot_machine_execute.go
Labels: automerge, autoupdate

#651 NOISSUE: fix benchmark scenario
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#643 PLAT-498: IsMessageFromVirtualLegitimate -> CheckMessageFromAuthorizedVirtual
  ledger-core/virtual/authentication/service.go
  ledger-core/virtual/authentication/service_mock.go
  ledger-core/virtual/authentication/service_test.go
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
Labels: automerge, autoupdate

#653 NOISSUE: fix bug with special base pulse
  ledger-core/insolar/payload/validation.go
Labels: automerge, autoupdate

#656 PLAT-685: add checks of VCallResult
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/insolar/payload/validation.go
  ledger-core/insolar/payload/validation_vcallresult.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/utils/vcallresult.go
Labels: automerge, autoupdate

#654 PLAT-291: move tests and remove duplicates
  ledger-core/virtual/integration/constructor_api_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/testwallet/method_api_test.go
  ledger-core/virtual/integration/testwallet/pulse_change_test.go
  ledger-core/virtual/integration/testwallet/scenario_test.go
Labels: autoupdate

#659 PLAT-730: tests refactoring
  ledger-core/virtual/integration/delegationtoken_test.go
Labels: automerge, autoupdate

#646 PLAT-469: test conveyor RestoreStep doesn't wake up SM
  ledger-core/conveyor/smachine/slot_machine_test.go
Labels: automerge, autoupdate

#658 PLAT-729: remove useless tests and change test with two reports
  ledger-core/virtual/integration/statereport_test.go
Labels: automerge, autoupdate

#661 PLAT-723: refactor test smv delegated call request
  ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
Labels: automerge, autoupdate

#645 NOISSUE: (Ledger) jet tree service
  ledger-core/ledger/jet/jet_id.go
  ledger-core/ledger/jet/jet_id_test.go
  ledger-core/ledger/server/buildersvc/service.go
  ledger-core/ledger/server/datawriter/smgenesis.go
  ledger-core/ledger/server/datawriter/smplash.go
  ledger-core/ledger/server/lmnapp/lmn_app.go
  ledger-core/ledger/server/lmnapp/lmn_app_test.go
  ledger-core/ledger/server/lmnapp/lmn_test_server.go
  ledger-core/ledger/server/treesvc/impl.go
  ledger-core/ledger/server/treesvc/service.go
Labels: autoupdate

#660 NOISSUE: better "preparing pulse" phase
  ledger-core/conveyor/conveyor.go
  ledger-core/conveyor/conveyor_test.go
  ledger-core/conveyor/conveyor_test.plantuml
  ledger-core/conveyor/pulse_manager.go
  ledger-core/conveyor/sm_pulse_slot.go
  ledger-core/conveyor/sm_pulse_slot.plantuml
  ledger-core/conveyor/smachine/slot.go
  ledger-core/conveyor/smachine/slot_machine.go
  ledger-core/conveyor/smachine/slot_machine_execute.go
Labels: automerge, autoupdate

#662 PLAT-732: fix CallIncoming and CallOutgoing fields in VDelegatedReque…
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
Labels: automerge, autoupdate

#648 NOISSUE: (Ledger) improved appctl
  ledger-core/cmd/keeperd/main.go
  ledger-core/cmd/pulsard/main.go
  ledger-core/cmd/testpulsard/main.go
  ledger-core/instrumentation/insapp/api_app.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/instrumentation/insconveyor/app_compart.go
  ledger-core/instrumentation/insconveyor/app_imposer.go
  ledger-core/instrumentation/insconveyor/instestconveyor/cycle_ctl.go
  ledger-core/instrumentation/insconveyor/instestconveyor/test_server.go
  ledger-core/instrumentation/insconveyor/worker.go
  ledger-core/instrumentation/inslogger/inslogger.go
  ledger-core/ledger/server/datawriter/smgenesis.go
  ledger-core/ledger/server/lmnapp/lmn_test_server.go
  ledger-core/ledger/server/lmnapp/lmntestapp/lmn_app_test.go
  ledger-core/ledger/server/lmnapp/lmntestapp/lmn_test_server.go
  ledger-core/network/servicenetwork/servicenetwork.go
  ledger-core/server/internal/headless/app_factory_test.go
  ledger-core/server/internal/virtual/app_factory_test.go
  ledger-core/testutils/journal/journal.go
  ledger-core/testutils/predicate/predicate_sm.go
Labels: autoupdate, ledger

#665 PLAT-731: fix TestVirtual_CallConstructorFromConstructor
  ledger-core/virtual/integration/constructor_test.go
Labels: automerge, autoupdate

#664 PLAT-733: fix undercounting
  ledger-core/conveyor/conveyor_test.go
Labels: automerge, autoupdate

#667 NOISSUE: Mute filtered events
  ledger-core/log/logcommon/redirector.go
  ledger-core/log/logcommon/redirector_test.go
Labels: automerge, autoupdate

#663 PLAT-734: don't save both semaphores in SmExecute. Use only required one
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_semiintegration_test.go
Labels: automerge, autoupdate

#652 PLAT-692: implement VCallRequest validation
  ledger-core/insolar/payload/delegationtokentype.go
  ledger-core/insolar/payload/validation.go
  ledger-core/insolar/payload/validation_vcallrequest.go
  ledger-core/insolar/payload/validation_vcallresult.go
  ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
  ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
  ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
  ledger-core/insolar/payload/vcallrequestflags.go
  ledger-core/network/messagesender/service.go
  ledger-core/runner/execution/rpc.go
  ledger-core/testutils/runner/logicless/service.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/benchs/semi_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/object_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/semaphore_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/utils/vcallrequest.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#655 PLAT-727: tests refactoring: simplify test
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#669 NOISSUE: minor changes in proto file
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/insolar/payload/validation_vcallrequest.go
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#670 PLAT-364: forward more info to ExecutionContinue
  ledger-core/runner/adapter.go
  ledger-core/runner/execution/eventsink.go
  ledger-core/runner/requestresult/outgoingresult.go
  ledger-core/runner/runner.go
  ledger-core/runner/runner_rpc.go
  ledger-core/testutils/runner/adapter/adapter.go
  ledger-core/testutils/runner/logicless/service.go
  ledger-core/virtual/execute/execute.go
Labels: automerge, autoupdate

#671 PLAT-665: fix flaky test virtual constructor prev pulse state with missing status
  ledger-core/virtual/integration/constructor_test.go
Labels: automerge, autoupdate

#672 PLAT-589: additional check pulse number in NewRecordOf
  ledger-core/reference/global.go
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute_isolation_negotiation_test.go
  ledger-core/virtual/execute/execute_publish_callsummary_test.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
Labels: automerge, autoupdate

#675 PLAT-736: callIncoming proper validation
  ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
  ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
  ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/utils/vcallrequest.go
Labels: automerge, autoupdate

#668 NOISSUE: isolate watermill
  ledger-core/appctl/beat/beat.go
  ledger-core/appctl/beat/dispatcher.go
  ledger-core/appctl/beat/dispatcher_mock.go
  ledger-core/appctl/beat/message.go
  ledger-core/instrumentation/insapp/api_app.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/instrumentation/insapp/utils_pubsub.go
  ledger-core/instrumentation/insconveyor/app_compart.go
  ledger-core/instrumentation/insconveyor/beat_dispatcher.go
  ledger-core/instrumentation/insconveyor/beat_dispatcher_test.go
  ledger-core/network/messagesender/router.go
  ledger-core/network/servicenetwork/servicenetwork.go
  ledger-core/network/servicenetwork/servicenetwork_test.go
  ledger-core/network/servicenetwork/watermill.go
  ledger-core/network/servicenetwork/watermill_router.go
  ledger-core/server/internal/virtual/wrapper.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/watermill_integration_test.go
Labels: autoupdate, ledger

#647 PLAT-664: rename vars and move waits
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
Labels: autoupdate

#674 NOISSUE: LRU/FIFO cache with low GC impact
  ledger-core/vanilla/cachekit/alloc.go
  ledger-core/vanilla/cachekit/cache_example.go
  ledger-core/vanilla/cachekit/core.go
  ledger-core/vanilla/cachekit/core_test.go
  ledger-core/vanilla/cachekit/strategy_test.go
Labels: autoupdate, ledger

#676 NOISSUE: refactor validation, code unification, more checks
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/insolar/payload/validation.go
  ledger-core/insolar/payload/validation_vcallrequest.go
  ledger-core/insolar/payload/validation_vcallresult.go
  ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
  ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
  ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
  ledger-core/insolar/payload/validation_vfindcallrequest.go
  ledger-core/insolar/payload/validation_vfindcallresponse.go
  ledger-core/insolar/payload/validation_vstatereport.go
  ledger-core/insolar/payload/validation_vstaterequest.go
  ledger-core/reference/global.go
  ledger-core/virtual/execute/execute_isolation_negotiation_test.go
  ledger-core/virtual/execute/execute_publish_callsummary_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/execute/migration_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/utils/server.go
Labels: automerge, autoupdate

#677 PLAT-365: make ExecutionContinue more sync
  ledger-core/runner/adapter.go
  ledger-core/runner/execution/eventsink.go
  ledger-core/runner/requestresult/outgoingresult.go
  ledger-core/runner/runner.go
  ledger-core/runner/runner_rpc.go
  ledger-core/testutils/runner/logicless/service.go
  ledger-core/virtual/execute/execute.go
Labels: automerge, autoupdate

#673 PLAT-728: Check asOf field in SMVStateReport
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/handlers/vstatereport.plantuml
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#678 NOISSUE: api echo
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/application/testwalletapi/statemachine/statemachine.plantuml
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/testutils/predicate/predicate_sm.go
  ledger-core/testutils/slotdebugger/stepmachine.go
Labels: automerge, autoupdate

#680 PLAT-735: TestVirtual_DeactivateObject panic
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#681 PLAT-740: signal from message checker is not reliable
  ledger-core/virtual/execute/execute_test.go
Labels: automerge, autoupdate

#682 NOISSUE: get rid of policy-bot
  .github/mergeable.yml
  .github/policy.yml
Labels: automerge, autoupdate

#683 PLAT-741: WaitActiveThenIdleConveyor doesn't give enough guranties
  ledger-core/virtual/integration/deactivate_test.go
Labels: automerge, autoupdate

#684 PLAT-726: Speedup tests
  ledger-core/Makefile.testing
  ledger-core/ledger/jet/prefix_tree_slow_test.go
  ledger-core/ledger/jet/prefix_tree_test.go
  ledger-core/network/gateway/watchers_test.go
  ledger-core/reference/marshal_holder_test.go
Labels: automerge, autoupdate

#619 PLAT-675: benchs for multi node setup with and without pulsar`
  ledger-core/application/benchs/api_utils_test.go
  ledger-core/application/benchs/multi_pulse_test.go
  ledger-core/application/benchs/single_pulse_test.go
  ledger-core/application/functest/api_test_utils.go
  ledger-core/application/functest/structures.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/go.mod
  ledger-core/go.sum
  ledger-core/scripts/generate_insolar_configs.go
  ledger-core/scripts/insolard/bootstrap_template.yaml
Labels: automerge, autoupdate

#685 PLAT-659: IncrementPulse can return when all checks are already failed
  ledger-core/virtual/integration/outgoing_test.go
Labels: automerge, autoupdate

#686 NOISSUE: ledger idempotent build
  ledger-core/conveyor/smachine/api_context.go
  ledger-core/conveyor/smachine/exec_adapter.go
  ledger-core/instrumentation/inslogger/logwatermill/watermill_adapter.go
  ledger-core/ledger/server/buildersvc/adapter.go
  ledger-core/ledger/server/buildersvc/drop_assist.go
  ledger-core/ledger/server/buildersvc/drop_assist_test.go
  ledger-core/ledger/server/buildersvc/entry_bundle.go
  ledger-core/ledger/server/buildersvc/plash_assist.go
  ledger-core/ledger/server/buildersvc/service.go
  ledger-core/ledger/server/datawriter/smline_data.go
  ledger-core/ledger/server/lineage/line_records.go
  ledger-core/ledger/server/lineage/line_staged.go
  ledger-core/ledger/server/lineage/line_staged_test.go
  ledger-core/ledger/server/lineage/record.go
  ledger-core/ledger/server/lineage/resolver_bundle.go
  ledger-core/ledger/server/lineage/update_bundle.go
  ledger-core/ledger/server/lmnapp/lmntestapp/record_builder.go
  ledger-core/ledger/server/lmnapp/tests/lmn_app_test.go
  ledger-core/ledger/server/requests/smregister.go
  ledger-core/rms/proto_catalog.pb.go
  ledger-core/rms/proto_catalog.proto
Labels: automerge, autoupdate, ledger

#687 NOISSUE: additional echo mode
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/application/testwalletapi/statemachine/handler.go
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
Labels: automerge, autoupdate

#694 PLAT-767: WaitStopOf should be called before SM is created
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/method_test.go
Labels: automerge, autoupdate

#697 NOISSUE: benchmarks
  .github/workflows/master-checks.yaml
  ledger-core/Makefile.testing
  ledger-core/application/benchs/api_utils_test.go
  ledger-core/application/benchs/multi_pulse_test.go
  ledger-core/application/benchs/single_pulse_test.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/go.mod
  ledger-core/go.sum
  ledger-core/scripts/insolard/launchnet.sh
Labels: automerge, autoupdate

#695 NOISSUE: rename polymorth to polymorph
  ledger-core/cmd/protoc-gen-ins/plugins/extra/polymorph.go
  ledger-core/insolar/payload/payload.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/ledger/server/lineage/record_aliases.go
  ledger-core/ledger/server/lmnapp/tests/lmn_app_test.go
  ledger-core/rms/proto_records.go
  ledger-core/rms/proto_records.pb.go
  ledger-core/rms/proto_vnlmn.pb.go
  ledger-core/rms/proto_vnvn.pb.go
Labels: automerge, autoupdate

#699 NOISSUE: fix pulsar default configuration for launchnet
  ledger-core/scripts/insolard/pulsar_template.yaml
Labels: automerge, autoupdate

#698 PLAT-55: add a couple of tests for context_exec
  ledger-core/conveyor/smachine/context_exec.go
  ledger-core/conveyor/smachine/context_exec_test.go
Labels: automerge, autoupdate

#700 PLAT-748: VCachedMemoryRequest, VCachedMemoryResponse
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
Labels: automerge, autoupdate

#701 NOISSUE: all .proto constants now have prefixes
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/application/testwalletapi/statemachine/handler.go
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/insolar/payload/validation.go
  ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
  ledger-core/insolar/payload/validation_vfindcallresponse.go
  ledger-core/insolar/payload/validation_vstatereport.go
  ledger-core/runner/bench_test.go
  ledger-core/runner/execution/rpc.go
  ledger-core/runner/runner.go
  ledger-core/runner/runner_test.go
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_isolation_negotiation_test.go
  ledger-core/virtual/execute/execute_publish_callsummary_test.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/execute/migration_test.go
  ledger-core/virtual/handlers/vcallresult.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/handlers/vfindcallrequest.go
  ledger-core/virtual/handlers/vfindcallrequest_test.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/handlers/vstatereport.plantuml
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/handlers/vstaterequest.go
  ledger-core/virtual/handlers/vstaterequest_test.go
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/benchs/semi_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/semaphore_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/staterequest_test.go
  ledger-core/virtual/integration/testwallet/pulse_change_test.go
  ledger-core/virtual/integration/utils/helper.go
  ledger-core/virtual/integration/utils/vcallrequest.go
  ledger-core/virtual/integration/utils/vcallresult.go
  ledger-core/virtual/integration/vdelegated_test.go
  ledger-core/virtual/integration/vstatereport_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go
Labels: automerge, autoupdate

#693 NOISSUE: faster hashing in LME
  ledger-core/crypto/legacyadapter/digest_512_as_224.go
  ledger-core/crypto/legacyadapter/digest_512_as_224_test.go
  ledger-core/crypto/legacyadapter/digest_record.go
  ledger-core/crypto/legacyadapter/record_scheme.go
Labels: automerge, autoupdate, ledger

#702 PLAT-773: add memoryCache adapter/service interfaces
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/memorycache/adapter/init.go
  ledger-core/virtual/memorycache/adapter/memory_cache_mock.go
  ledger-core/virtual/memorycache/service.go
  ledger-core/virtual/memorycache/service_mock.go
  ledger-core/virtual/virtual.go
Labels: autoupdate

#703 PLAT-773: change MemoryCache.Set method
  ledger-core/virtual/memorycache/service.go
  ledger-core/virtual/memorycache/service_mock.go
Labels: automerge, autoupdate

#705 NOISSUE: minor SMObject refactoring
  ledger-core/virtual/object/info_test.go
  ledger-core/virtual/object/object.go
Labels: automerge, autoupdate

#707 PLAT-754: stub of VObjectTranscriptReport message
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/handlers/vobjecttranscriptreport.go
  ledger-core/virtual/handlers/vobjecttranscriptreport.plantuml
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
Labels: automerge, autoupdate

#706 PLAT-752: handlers for cached memory request
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.plantuml
  ledger-core/virtual/handlers/vcachedmemoryresponse.go
  ledger-core/virtual/handlers/vcachedmemoryresponse.plantuml
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
Labels: automerge, autoupdate

#710 PLAT-751: add SMVCachedMemoryRequest
  ledger-core/insolar/payload/marker_auth.go
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.plantuml
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/vcachedmemoryrequest_test.go
  ledger-core/virtual/memorycache/adapter/init.go
  ledger-core/virtual/virtual.go
Labels: automerge, autoupdate

#708 PLAT-778: run func tests on insolard in cloud mode
  ledger-core/Makefile.testing
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/cmd/insolard/cloud.go
  ledger-core/cmd/insolard/commands.go
  ledger-core/configuration/configuration.go
  ledger-core/runner/executor/builtin/proxyhelper.go
  ledger-core/scripts/cloud/generate_cloud_config.go
  ledger-core/scripts/insolard/launchnet.sh
  ledger-core/server/server.go
Labels: automerge, autoupdate

#712 PLAT-754: move to rms package and add minimal entries
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/proto_vnvn.proto
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/handlers/vobjecttranscriptreport.go
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
  ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/main.go
  ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/template.go
Labels: automerge, autoupdate

#713 NOISSUE: remove unused code
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/handlers/vobjecttranscriptreport.go
  ledger-core/virtual/handlers/vstaterequest.go
Labels: automerge, autoupdate

#709 PLAT-752: add new test for VCachedMemoryRequest
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/utils/vstatereport.go
Labels: automerge, autoupdate

#714 PLAT-750: Set Memory after delegation and ordered call
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/instrumentation/insconveyor/beat_dispatcher.go
  ledger-core/network/messagesender/adapter/init.go
  ledger-core/server/internal/virtual/app_factory.go
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/memorycache/adapter/init.go
  ledger-core/virtual/testutils/virtualdebugger/stepmachine.go
Labels: automerge, autoupdate

#718 PLAT-772: simple memory cache
  ledger-core/virtual/integration/vcachedmemoryrequest_test.go
  ledger-core/virtual/memorycache/cache.go
  ledger-core/virtual/memorycache/service.go
Labels: automerge, autoupdate
