Repository insolar/assured-ledger, pull requests merged in 2020-09, with the labels that each got.

#719 PLAT-752: remove debug test and unskip good tests
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/vcachedmemoryrequest_test.go
Labels: automerge, autoupdate

#717 PLAT-755: stab structures for collecting transcripts
  ledger-core/virtual/object/object.go
  ledger-core/virtual/validation/entries.go
  ledger-core/virtual/validation/transcript.go
Labels: automerge, autoupdate

#721 NOISSUE: Don't generate unused files in launchnet.sh
  ledger-core/scripts/insolard/launchnet.sh
Labels: automerge, autoupdate

#720 NOISSUE: ledger verify
  ledger-core/ledger/server/buildersvc/entry_bundle.go
  ledger-core/ledger/server/catalog/excerpt_test.go
  ledger-core/ledger/server/datawriter/smline_catalog.go
  ledger-core/ledger/server/datawriter/smline_data.go
  ledger-core/ledger/server/inspectsvc/records.go
  ledger-core/ledger/server/inspectsvc/service.go
  ledger-core/ledger/server/lineage/line_staged.go
  ledger-core/ledger/server/lmnapp/event_factory.go
  ledger-core/ledger/server/lmnapp/tests/lmn_app_test.go
  ledger-core/ledger/server/requests/smregister.go
  ledger-core/rms/any_record_lazy.go
  ledger-core/rms/proto_catalog.pb.go
  ledger-core/rms/proto_catalog.proto
  ledger-core/rms/proto_vnlmn.go
  ledger-core/rms/proto_vnlmn.pb.go
  ledger-core/rms/proto_vnlmn.proto
  ledger-core/rms/record_body.go
  ledger-core/rms/record_body_digest.go
  ledger-core/rms/rms.go
  ledger-core/rms/rms.proto
  ledger-core/scripts/insolard/launchnet.sh
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/vcachedmemoryrequest_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/validation/entries.go
  ledger-core/virtual/validation/transcript.go
Labels: automerge, autoupdate, ledger

#726 HOTFIX: disable annoying codecov annotations
  .github/codecov.yml
Labels: automerge, autoupdate

#725 NOISSUE: ever open sync
  ledger-core/conveyor/smachine/api_sync.go
  ledger-core/conveyor/smachine/smsync/sync_ever.go
  ledger-core/conveyor/smachine/smsync/sync_never.go
Labels: autoupdate

#728 NOISSUE: nsh from ledger
  ledger-core/conveyor/conveyor.go
  ledger-core/conveyor/pulse_manager.go
  ledger-core/conveyor/pulse_slot.go
  ledger-core/conveyor/sm_pulse_slot.go
  ledger-core/ledger/server/buildersvc/drop_assist_test.go
  ledger-core/ledger/server/buildersvc/plash_assist.go
  ledger-core/ledger/server/buildersvc/service.go
  ledger-core/ledger/server/datawriter/smplash.go
Labels: autoupdate, ledger

#732 NOISSUE: Fix journal for race
  ledger-core/testutils/journal/disp.go
  ledger-core/testutils/journal/journal.go
Labels: automerge, autoupdate

#731 PLAT-784: refactor object reference in tests
  ledger-core/virtual/callregistry/request_table_test.go
  ledger-core/virtual/callregistry/working_table_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
  ledger-core/virtual/handlers/vdelegatedcallresponse_test.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished_test.go
  ledger-core/virtual/handlers/vfindcallrequest_test.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/handlers/vstaterequest_test.go
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/testwallet/pulse_change_test.go
  ledger-core/virtual/integration/utils/vcallresult.go
  ledger-core/virtual/object/info_test.go
  ledger-core/virtual/object/object_migration_test.go
  ledger-core/virtual/object/object_test.go
  ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go
Labels: automerge, autoupdate

#733 PLAT-785: outgoing and gen.UniqueGlobalRef() refactoring
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/sender_test.go
  ledger-core/virtual/integration/utils/helper.go
  ledger-core/virtual/integration/utils/wallet.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#737 NOISSUE: Isolate PulseManager
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/pulse_manager.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/network/servicenetwork/servicenetwork.go
Labels: automerge, autoupdate

#741 NOISSUE: Check marshal size
  ledger-core/cmd/protoc-gen-ins/plugins/gogobased/marshalto.go
  ledger-core/insolar/payload/payload.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/rms/proto_catalog.pb.go
  ledger-core/rms/proto_legacy.pb.go
  ledger-core/rms/proto_records.pb.go
  ledger-core/rms/proto_vnlmn.pb.go
  ledger-core/rms/proto_vnvn.pb.go
Labels: automerge, autoupdate

#739 NOISSUE: AcquireExt method
  ledger-core/conveyor/smachine/api_sync.go
  ledger-core/conveyor/smachine/context_basic.go
  ledger-core/conveyor/smachine/execution_context_mock.go
  ledger-core/conveyor/smachine/initialization_context_mock.go
  ledger-core/conveyor/smachine/migration_context_mock.go
Labels: automerge, autoupdate

#729 PLAT-795: check not nil
  ledger-core/vanilla/cachekit/core.go
Labels: automerge, autoupdate

#736 PLAT-790: delete incrementPulse
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/semaphore_test.go
Labels: automerge, autoupdate

#742 PLAT-763: add VObjectValidationReport msg
  ledger-core/insolar/payload/marker_auth.go
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/handlers/vobjectvalidationreport.go
  ledger-core/virtual/handlers/vobjectvalidationreport.plantuml
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
Labels: automerge, autoupdate

#734 PLAT-773: update memory cache service
  ledger-core/insolar/payload/proto_vnvn.r0.pb.go
  ledger-core/insolar/payload/proto_vnvn.r0.proto
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/memorycache/cache_test.go
  ledger-core/virtual/memorycache/service.go
  ledger-core/virtual/memorycache/service_mock.go
Labels: automerge, autoupdate

#738 NOISSUE: cryptkit refactoring
  ledger-core/crypto/legacyadapter/default_scheme.go
  ledger-core/crypto/legacyadapter/record_scheme.go
  ledger-core/crypto/legacyadapter/signer.go
  ledger-core/crypto/legacyadapter/signer_test.go
  ledger-core/network/consensus/adapters/factory.go
  ledger-core/network/consensus/adapters/profile.go
  ledger-core/network/consensus/common/endpoints/addrs.go
  ledger-core/network/consensus/common/endpoints/addrs_test.go
  ledger-core/network/consensus/common/endpoints/inbound_mock.go
  ledger-core/network/consensus/gcpv2/api/misbehavior/blame_factory_test.go
  ledger-core/network/consensus/gcpv2/api/misbehavior/fraud_factory_test.go
  ledger-core/network/consensus/gcpv2/api/profiles/candidate_profile_mock.go
  ledger-core/network/consensus/gcpv2/api/profiles/node_profiles.go
  ledger-core/network/consensus/gcpv2/api/profiles/static_impl.go
  ledger-core/network/consensus/gcpv2/api/profiles/static_profile_mock.go
  ledger-core/network/consensus/gcpv2/api/proofs/cloud_state_hash_mock.go
  ledger-core/network/consensus/gcpv2/api/proofs/globula_state_hash_mock.go
  ledger-core/network/consensus/gcpv2/api/proofs/member_announcement_signature_mock.go
  ledger-core/network/consensus/gcpv2/api/proofs/node_state_hash_evidence_mock.go
  ledger-core/network/consensus/gcpv2/api/proofs/node_state_hash_mock.go
  ledger-core/network/consensus/gcpv2/api/transport/full_introduction_reader_mock.go
  ledger-core/network/consensus/gcpv2/censusimpl/assignment_perf_test.go
  ledger-core/network/consensus/serialization/packet_reader.go
  ledger-core/network/consensus/tests/chronicles_test.go
  ledger-core/network/consensus/tests/transport_test.go
  ledger-core/testutils/network/mutable/node.go
  ledger-core/testutils/testpop/population.go
  ledger-core/vanilla/cryptkit/cert.go
  ledger-core/vanilla/cryptkit/certificate_holder_mock.go
  ledger-core/vanilla/cryptkit/ciphers.go
  ledger-core/vanilla/cryptkit/containers.go
  ledger-core/vanilla/cryptkit/containers_test.go
  ledger-core/vanilla/cryptkit/digest.go
  ledger-core/vanilla/cryptkit/digest_holder_mock.go
  ledger-core/vanilla/cryptkit/key_store_factory_mock.go
  ledger-core/vanilla/cryptkit/keystore.go
  ledger-core/vanilla/cryptkit/signature.go
  ledger-core/vanilla/cryptkit/signature_holder_mock.go
  ledger-core/vanilla/cryptkit/signature_key_holder_mock.go
  ledger-core/vanilla/cryptkit/signature_verifier_mock.go
  ledger-core/vanilla/cryptkit/signing_key_holder_mock.go
Labels: automerge, autoupdate

#743 PLAT-779: Multinode controller
  ledger-core/appctl/beat/memstor/memory.go
  ledger-core/cmd/insolard/cloud.go
  ledger-core/cmd/insolard/main.go
  ledger-core/configuration/configuration.go
  ledger-core/conveyor/pulse_slot.go
  ledger-core/instrumentation/insapp/api_app.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/pulse_manager.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/instrumentation/insconveyor/app_compart.go
  ledger-core/instrumentation/insconveyor/instestconveyor/test_server.go
  ledger-core/ledger/server/lmnapp/lmntestapp/record_builder.go
  ledger-core/network/servicenetwork/servicenetwork.go
  ledger-core/network/servicenetwork/servicenetwork_test.go
  ledger-core/network/servicenetwork/watermill.go
  ledger-core/network/watermill/router.go
  ledger-core/scripts/cloud/generate_cloud_config.go
  ledger-core/scripts/generate_insolar_configs.go
  ledger-core/scripts/insolard/pulsar_template.yaml
  ledger-core/server/factory.go
  ledger-core/server/internal/cloud/controller.go
  ledger-core/server/internal/cloud/network.go
  ledger-core/server/internal/cloud/pulsar.go
  ledger-core/server/internal/headless/app_factory_test.go
  ledger-core/server/internal/virtual/app_factory_test.go
  ledger-core/server/server.go
Labels: automerge, autoupdate

#745 NOISSUE: 30m is not enough for integration tests on GHA
  ledger-core/Makefile.testing
Labels: automerge, autoupdate

#735 PLAT-781: mnp configuration
  ledger-core/cmd/insolard/cloud.go
  ledger-core/instrumentation/insapp/cloud_configuration.go
  ledger-core/instrumentation/insapp/cloud_test.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/scripts/insolard/bootstrap_template.yaml
  ledger-core/scripts/insolard/launchnet.sh
  ledger-core/server/internal/cloud/pulsar.go
  ledger-core/server/server.go
Labels: automerge, autoupdate

#748 NOISSUE: Access control flag for shared data
  ledger-core/conveyor/smachine/api_context.go
  ledger-core/conveyor/smachine/api_shared_link.go
  ledger-core/conveyor/smachine/slot_machine.go
Labels: automerge, autoupdate

#749 NOISSUE: Fix rollback test ordering
  ledger-core/ledger/server/buildersvc/bundle/api_writer.go
  ledger-core/ledger/server/buildersvc/bundle/writeable_mock.go
  ledger-core/ledger/server/buildersvc/bundle/writer_test.go
Labels: automerge, autoupdate

#747 PLAT-787: refactor mock to outgoing
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
Labels: automerge, autoupdate

#753 NOISSUE: improved time tracking
  ledger-core/conveyor/smachine/slot.go
  ledger-core/conveyor/smachine/slot_bargein.go
  ledger-core/conveyor/smachine/slot_machine_execute.go
  ledger-core/conveyor/smachine/slot_machine_migrate.go
  ledger-core/instrumentation/convlog/logger.go
Labels: automerge, autoupdate

#757 NOISSUE: PulseSlot race fix
  ledger-core/conveyor/conveyor.go
  ledger-core/conveyor/sm_pulse_slot.go
Labels: automerge, autoupdate

#758 NOISSUE: enforce Any marshaling
  ledger-core/rms/any.go
  ledger-core/rms/registry.go
  ledger-core/virtual/integration/mock/publisher/checker/typed.go
  ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/template.go
Labels: automerge, autoupdate

#751 PLAT-793: add func tests on cloud
  ledger-core/Makefile.testing
  ledger-core/application/testutils/launchnet/cloud.go
  ledger-core/application/testutils/launchnet/cloud_with_consensus.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/application/testutils/launchnet/runner.go
  ledger-core/instrumentation/insapp/cloud_configuration.go
  ledger-core/instrumentation/insapp/cloud_test.go
  ledger-core/scripts/insolard/launchnet.sh
  ledger-core/server/server.go
Labels: automerge, autoupdate

#750 PLAT-788: executionMock to interface
  ledger-core/testutils/runner/logicless/service.go
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/outgoing_test.go
  ledger-core/virtual/integration/semaphore_test.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#756 PLAT-806: add ga actions
  .github/workflows/linux-checks.yaml
  .github/workflows/master-checks.yaml
  ledger-core/application/testutils/launchnet/cloud.go
  ledger-core/cmd/insolard/cloud.go
  ledger-core/instrumentation/insapp/cloud_test.go
Labels: automerge, autoupdate

#766 NOISSUE: refactor Meta message
  ledger-core/network/messagesender/service.go
  ledger-core/network/servicenetwork/servicenetwork_test.go
  ledger-core/rms/proto_vnvn.r0.pb.go
  ledger-core/rms/proto_vnvn.r0.proto
  ledger-core/runner/execution/rpc.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/handle_meta.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/handlers/vdelegatedcallrequest.go
  ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
  ledger-core/virtual/handlers/vfindcallrequest.go
  ledger-core/virtual/handlers/vfindcallrequest_test.go
  ledger-core/virtual/handlers/vstaterequest.go
  ledger-core/virtual/handlers/vstaterequest_test.go
  ledger-core/virtual/integration/utils/message.go
Labels: automerge, autoupdate

#767 NOISSUE: transport providers
  ledger-core/network/nds/uniproto/l2/uniserver/api_transport.go
  ledger-core/network/nds/uniproto/l2/uniserver/server.go
Labels: autoupdate

#760 NOISSUE: atomickit improvements
  ledger-core/vanilla/atomickit/bool.go
  ledger-core/vanilla/atomickit/bytestring.go
  ledger-core/vanilla/atomickit/flag_once.go
  ledger-core/vanilla/atomickit/flag_startstop.go
  ledger-core/vanilla/atomickit/int.go
  ledger-core/vanilla/atomickit/int32.go
  ledger-core/vanilla/atomickit/int64.go
  ledger-core/vanilla/atomickit/once.go
  ledger-core/vanilla/atomickit/uint.go
  ledger-core/vanilla/atomickit/uint32.go
  ledger-core/vanilla/atomickit/uint64.go
Labels: automerge, autoupdate

#770 NOISSUE: Nicify rms legacy
  ledger-core/rms/proto_legacy_profile.pb.go
  ledger-core/rms/proto_legacy_profile.proto
  ledger-core/rms/rms.go
Labels: automerge, autoupdate

#773 NOISSUE: fix for long running tests
  ledger-core/testutils/pulsegenerator.go
  ledger-core/virtual/integration/object_test.go
  ledger-core/virtual/integration/utils/server.go
Labels: automerge, autoupdate

#768 PLAT-822: added MaxRunners param to node config
  ledger-core/configuration/configuration.go
  ledger-core/configuration/testdata/changed.yml
  ledger-core/configuration/testdata/default.yml
  ledger-core/configuration/virtual.go
  ledger-core/scripts/deploy/kube/10node/configuration/virtual-config.yaml
  ledger-core/scripts/deploy/kube/15node/configuration/virtual-config.yaml
  ledger-core/scripts/deploy/kube/20node/configuration/virtual-config.yaml
  ledger-core/scripts/deploy/kube/40node/configuration/virtual-config.yaml
  ledger-core/scripts/deploy/kube/5node/configuration/virtual-config.yaml
  ledger-core/scripts/deploy/kube/80node/configuration/virtual-config.yaml
  ledger-core/scripts/deploy/kube/manifests/configuration/virtual-config.yaml
  ledger-core/server/internal/virtual/app_factory.go
Labels: automerge, autoupdate

#761 PLAT-804: benches on cloud
  .github/workflows/linux-checks.yaml
  ledger-core/application/benchs/benchrunner_test.go
  ledger-core/application/benchs/cloud_test.go
  ledger-core/application/benchs/fullnetwork_test.go
  ledger-core/application/benchs/limiter_test.go
  ledger-core/application/benchs/multi_pulse_test.go
  ledger-core/application/benchs/single_pulse_test.go
  ledger-core/application/testutils/launchnet/cloud.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/application/testutils/launchnet/runner.go
  ledger-core/application/testwalletapi/testwalletserver.go
  ledger-core/cmd/pulsard/main.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/server/internal/cloud/pulsar.go
Labels: automerge, autoupdate

#778 NOISSUE: parent concept doesn't work and don't know when we will add it back
  ledger-core/runner/requestresult/requestresult.go
  ledger-core/runner/runner.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/contract_calls_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/outgoing_test.go
Labels: automerge, autoupdate

#779 NOISSUE: state id from RequestResult is not used anywhere
  ledger-core/runner/requestresult/requestresult.go
  ledger-core/virtual/execute/execute.go
Labels: automerge, autoupdate

#776 PLAT-823: cloud logs
  .github/workflows/linux-checks.yaml
  .github/workflows/master-checks.yaml
  .github/workflows/windows-checks.yaml
  ledger-core/application/api/instrumenter/instrumenter.go
  ledger-core/application/api/main.go
  ledger-core/application/api/main_test.go
  ledger-core/application/api/seed.go
  ledger-core/application/api/seed_test.go
  ledger-core/application/api/status.go
  ledger-core/application/functest/main_func_test.go
  ledger-core/application/testutils/launchnet/cloud.go
  ledger-core/application/testutils/launchnet/cloud_configuration.go
  ledger-core/application/testutils/launchnet/cloud_test.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/application/testwalletapi/handlers.go
  ledger-core/application/testwalletapi/testwalletserver.go
  ledger-core/cmd/insolard/cloud.go
  ledger-core/cmd/insolard/main.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/server/internal/cloud/pulsar.go
  ledger-core/server/internal/virtual/app_factory.go
  ledger-core/server/internal/virtual/wrapper.go
  ledger-core/server/server.go
  ledger-core/virtual/integration/utils/server.go
Labels: automerge, autoupdate

#781 NOISSUE: fix benchmarks
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#782 PLAT-830: disable time related checks for now
  ledger-core/log/global/struct_log_test.go
Labels: autoupdate

#783 NOISSUE: set journal predicate before payload is sent
  ledger-core/virtual/integration/staterequest_test.go
Labels: automerge, autoupdate

#784 NOISSUE: store all logs from master checks
  .github/workflows/master-checks.yaml
Labels: automerge, autoupdate

#744 NOISSUE: fix msgdelivery
  ledger-core/network/nds/msgdelivery/controller.go
  ledger-core/network/nds/msgdelivery/controller_bench_test.go
  ledger-core/network/nds/msgdelivery/controller_massive_send_test.go
  ledger-core/network/nds/msgdelivery/controller_test.go
  ledger-core/network/nds/msgdelivery/ctl_dedup.go
  ledger-core/network/nds/msgdelivery/ctl_dedup_test.go
  ledger-core/network/nds/msgdelivery/ctl_retry_msg.go
  ledger-core/network/nds/msgdelivery/ctl_retry_msg_worker.go
  ledger-core/network/nds/msgdelivery/protocol_test.go
  ledger-core/network/nds/msgdelivery/retries/staged.go
  ledger-core/network/nds/msgdelivery/shipment_msg.go
  ledger-core/network/nds/msgdelivery/uniproto_utils_test.go
  ledger-core/network/nds/uniproto/l1/tcp.go
  ledger-core/network/nds/uniproto/l2/uniserver/peer_manager.go
  ledger-core/network/nds/uniproto/l2/uniserver/peer_map.go
  ledger-core/network/nds/uniproto/l2/uniserver/server.go
Labels: autoupdate

#794 NOISSUE: failed to marshal/unmarshal AnyLazy fix
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/proto_vnvn.proto
  ledger-core/rms/rmsbox/any_lazy.go
  ledger-core/rms/tests/any_record_lazy_test.go
Labels: automerge, autoupdate

#788 PLAT-829: manual pulsar
  ledger-core/application/benchs/benchrunner_test.go
  ledger-core/application/benchs/cloud_test.go
  ledger-core/application/testutils/launchnet/cloud.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/instrumentation/insconveyor/instestconveyor/test_server.go
  ledger-core/server/server.go
  ledger-core/testutils/cloud/controller.go
  ledger-core/testutils/cloud/controller_test.go
  ledger-core/testutils/cloud/network.go
  ledger-core/testutils/cloud/pulsar.go
  ledger-core/testutils/pulsegenerator.go
  ledger-core/testutils/pulsegenerator_test.go
  ledger-core/virtual/integration/utils/server.go
Labels: automerge, autoupdate

#800 NOISSUE: benchmark run fix
  .github/workflows/master-checks.yaml
  ledger-core/Makefile.testing
Labels: automerge, autoupdate

#802 NOISSUE: rms.NewAny function
  ledger-core/rms/rms.go
  ledger-core/rms/rmsbox/any.go
Labels: automerge, autoupdate

#801 NOISSUE: Don't redirect to file output of test runs
  .github/workflows/master-checks.yaml
Labels: automerge, autoupdate

#804 NOISSUE: any for message with payloads
  ledger-core/rms/rmsbox/any.go
  ledger-core/rms/rmsbox/any_lazy.go
  ledger-core/rms/rmsbox/any_record_lazy.go
  ledger-core/rms/rmsbox/basic.go
  ledger-core/rms/rmsbox/message.go
  ledger-core/rms/rmsbox/record_payloads.go
  ledger-core/rms/rmsreg/registry.go
  ledger-core/rms/rmsreg/serializable.go
  ledger-core/rms/tests/proto_test.go
Labels: automerge, autoupdate

#803 PLAT-837: Fixed package size check limits
  ledger-core/network/nds/uniproto/api_packet_send.go
  ledger-core/network/nds/uniproto/l2/uniserver/peer_transport.go
Labels: autoupdate

#808 NOISSUE: add traceid to error description in functests
  ledger-core/application/functest/api_test_utils.go
Labels: automerge, autoupdate
