Repository insolar/assured-ledger, pull requests merged in 2020-10, with the labels that each got.

#809 NOISSUE: manual trigger for consensus checks
  .github/workflows/consensus-checks.yaml
Labels: automerge, autoupdate

#811 NOISSUE: migration delayed by replace was not applied after init
  ledger-core/conveyor/smachine/slot_machine_execute.go
  ledger-core/conveyor/smachine/slot_machine_test.go
Labels: automerge, autoupdate

#816 NOISSUE: TestController_PartialDistribute: fix logging
  ledger-core/testutils/cloud/controller_test.go
Labels: automerge, autoupdate

#813 NOISSUE: replace should inherit migration status from origin
  ledger-core/virtual/execute/execute.go
Labels: automerge, autoupdate

#805 PLAT-836: Panic listen udp
  ledger-core/network/nds/msgdelivery/controller.go
  ledger-core/network/nds/msgdelivery/controller_massive_send_test.go
  ledger-core/network/nds/msgdelivery/controller_test.go
  ledger-core/network/nds/msgdelivery/ctl_retry_map.go
  ledger-core/network/nds/msgdelivery/ctl_retry_map_test.go
  ledger-core/network/nds/msgdelivery/ctl_retry_msg.go
  ledger-core/network/nds/msgdelivery/ctl_starter.go
  ledger-core/network/nds/msgdelivery/packet_parcel.go
  ledger-core/network/nds/msgdelivery/peer.go
  ledger-core/network/nds/msgdelivery/protocol_test.go
  ledger-core/network/nds/msgdelivery/uniproto_utils_test.go
  ledger-core/network/nds/uniproto/l1/udp.go
  ledger-core/network/nds/uniproto/l2/uniserver/peer_manager.go
  ledger-core/network/nds/uniproto/l2/uniserver/server.go
  ledger-core/network/nwapi/serializable.go
Labels: automerge, autoupdate

#752 PLAT-820: Finalizer for SM
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/conveyor/smachine/api_context.go
  ledger-core/conveyor/smachine/api_panic.go
  ledger-core/conveyor/smachine/api_state_machine.go
  ledger-core/conveyor/smachine/context_async.go
  ledger-core/conveyor/smachine/context_basic.go
  ledger-core/conveyor/smachine/context_exec.go
  ledger-core/conveyor/smachine/context_misc.go
  ledger-core/conveyor/smachine/context_share_publish.go
  ledger-core/conveyor/smachine/exec_adapter.go
  ledger-core/conveyor/smachine/execution_context_mock.go
  ledger-core/conveyor/smachine/initialization_context_mock.go
  ledger-core/conveyor/smachine/main/example/example_3.go
  ledger-core/conveyor/smachine/migration_context_mock.go
  ledger-core/conveyor/smachine/slot.go
  ledger-core/conveyor/smachine/slot_bargein.go
  ledger-core/conveyor/smachine/slot_error.go
  ledger-core/conveyor/smachine/slot_machine.go
  ledger-core/conveyor/smachine/slot_machine_migrate.go
  ledger-core/conveyor/smachine/slot_machine_test.go
  ledger-core/conveyor/smachine/slot_subroutine.go
  ledger-core/conveyor/smachine/sm_finalize_test.go
  ledger-core/conveyor/smachine/sm_helper_test.go
  ledger-core/conveyor/smachine/sm_migrate_test.go
  ledger-core/conveyor/smachine/sm_replace_test.go
  ledger-core/conveyor/smachine/sm_restore_test.go
  ledger-core/conveyor/smachine/state_update_type.go
  ledger-core/conveyor/smachine/state_updates.go
  ledger-core/ledger/server/buildersvc/adapter.go
  ledger-core/ledger/server/requests/smregister.go
Labels: automerge, autoupdate

#817 NOISSUE: pulse change error on conveyor stop
  ledger-core/conveyor/conveyor.go
  ledger-core/instrumentation/insconveyor/beat_dispatcher.go
Labels: automerge, autoupdate

#818 NOISSUE: fix pointer conversion in rms
  ledger-core/rms/rmsbox/any_lazy.go
  ledger-core/rms/rmsreg/registry.go
Labels: automerge, autoupdate

#820 PLAT-843: Fixed message delivery (benchmark hangs)
  ledger-core/network/nds/msgdelivery/ctl_dedup.go
  ledger-core/network/nds/msgdelivery/ctl_retry_state_worker.go
Labels: automerge, autoupdate

#819 NOISSUE: Protection of AffectedStep
  ledger-core/conveyor/smachine/api_context.go
  ledger-core/conveyor/smachine/context_async.go
  ledger-core/conveyor/smachine/context_basic.go
  ledger-core/conveyor/smachine/context_misc.go
  ledger-core/conveyor/smachine/slot_bargein.go
  ledger-core/conveyor/smachine/slot_error.go
  ledger-core/conveyor/smachine/slot_machine_migrate.go
  ledger-core/conveyor/smachine/slot_subroutine.go
  ledger-core/conveyor/smachine/state_update_type.go
Labels: automerge, autoupdate

#814 PLAT-839: rework bootstrap reconnect host
  ledger-core/appctl/beat/node_manager.go
  ledger-core/network/gateway/base.go
  ledger-core/network/gateway/bootstrap/permit.go
  ledger-core/network/gateway/bootstrap/requester.go
  ledger-core/network/gateway/complete.go
  ledger-core/network/gateway/gatewayer.go
  ledger-core/network/gateway/gatewayer_test.go
  ledger-core/network/gateway/nonetwork.go
  ledger-core/network/interfaces.go
  ledger-core/rms/proto_legacy_packet.pb.go
  ledger-core/rms/proto_legacy_packet.proto
  ledger-core/scripts/generate_insolar_configs.go
  ledger-core/testutils/network/gateway_mock.go
Labels: automerge, autoupdate

#822 NOISSUE: fix test failure on forbidden port
  .github/workflows/windows-checks.yaml
  ledger-core/network/nds/msgdelivery/uniproto_utils_test.go
  ledger-core/network/nds/uniproto/l2/uniserver/server.go
  ledger-core/network/nds/uniproto/l2/uniserver/server_check_wrappers_test.go
  ledger-core/network/nds/uniproto/l2/uniserver/server_ptf.go
  ledger-core/network/nds/uniproto/l2/uniserver/server_test.go
Labels: automerge, autoupdate

#824 NOISSUE: fix benchmarks that stopped working after register
  ledger-core/application/benchs/cloud_test.go
  ledger-core/application/benchs/fullnetwork_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/benchs/semi_test.go
Labels: automerge, autoupdate

#826 NOISSUE: remove PreviousState that is legacy of platform1
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/proto_vnvn.proto
  ledger-core/virtual/integration/memory_request_test.go
Labels: automerge, autoupdate

#827 NOISSUE: State is too often used keyword
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/proto_vnvn.proto
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/vdelegatedrequestfinished.go
  ledger-core/virtual/handlers/vstatereport.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/staterequest_test.go
  ledger-core/virtual/integration/testwallet/pulse_change_test.go
  ledger-core/virtual/integration/utils/vstatereport.go
  ledger-core/virtual/integration/vdelegated_test.go
  ledger-core/virtual/integration/vstatereport_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go
Labels: automerge, autoupdate

#828 NOISSUE: disable keeperd in functests
  ledger-core/application/api/availability.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/scripts/insolard/launchnet.sh
  ledger-core/virtual/execute/execute_test.go
Labels: automerge, autoupdate

#825 PLAT-257: update consensus-checks workflow
  .github/mergeable.yml
  .github/workflows/consensus-checks.yaml
  ledger-core/scripts/deploy/kube/report-add-range.yaml
  ledger-core/scripts/deploy/kube/report.yaml
Labels: automerge, autoupdate, hacktoberfest-accepted

#832 PLAT-846: validate methods for VCachedMemoryRequest/Response
  ledger-core/rms/proto_vnvn_validation.go
  ledger-core/rms/proto_vnvn_validation_vcachedmemoryrequest.go
  ledger-core/rms/proto_vnvn_validation_vcachedmemoryresponse.go
Labels: automerge, autoupdate

#833 NOISSUE: new msg validations
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/proto_vnvn.proto
  ledger-core/rms/proto_vnvn_validation_vobjecttranscriptreport.go
Labels: automerge, autoupdate

#834 NOISSUE: update `set-env` and `add-path` in GHA workflows
  .github/workflows/consensus-checks.yaml
  .github/workflows/linux-checks.yaml
  .github/workflows/long-integration.yaml
  .github/workflows/master-checks.yaml
  .github/workflows/windows-checks.yaml
Labels: automerge, autoupdate

#831 NOISSUE: add dry run for SubSMRegister
  ledger-core/virtual/lmn/register.go
  ledger-core/virtual/lmn/register.plantuml
Labels: automerge, autoupdate

#836 NOISSUE: jww cleanup
  ledger-core/cmd/insolard/cloud.go
  ledger-core/cmd/insolard/main.go
  ledger-core/cmd/keeperd/main.go
  ledger-core/cmd/pulsard/main.go
  ledger-core/cmd/testpulsard/main.go
  ledger-core/go.mod
  ledger-core/go.sum
Labels: automerge, autoupdate

#835 NOISSUE: refactor pulsewatcher to component
  ledger-core/application/cmd/insolar/create_default_configs.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/application/testutils/launchnet/runner.go
  ledger-core/cmd/pulsewatcher/README.md
  ledger-core/cmd/pulsewatcher/config/pulsewatcher.go
  ledger-core/cmd/pulsewatcher/pulsewatcher.go
  ledger-core/configuration/pulsewatcher.go
  ledger-core/pulsewatcher/output/json/json.go
  ledger-core/pulsewatcher/output/output.go
  ledger-core/pulsewatcher/output/text/emoji.go
  ledger-core/pulsewatcher/output/text/text.go
  ledger-core/pulsewatcher/runner.go
  ledger-core/pulsewatcher/status/node.go
  ledger-core/scripts/generate_insolar_configs.go
  ledger-core/scripts/insolard/launchnet.sh
  ledger-core/scripts/insolard/pulsewatcher_template.yaml
Labels: automerge, autoupdate

#837 NOISSUE: rmsbox.Reference support for explicit empty value
  ledger-core/rms/rmsbox/binary.go
  ledger-core/rms/rmsbox/record_body.go
  ledger-core/rms/rmsbox/record_payloads.go
  ledger-core/rms/rmsbox/reference.go
  ledger-core/rms/rmsbox/reference_test.go
  ledger-core/vanilla/protokit/binary.go
  ledger-core/vanilla/protokit/binary_test.go
Labels: automerge, autoupdate

#838 NOISSUE: improve UnmarshalWithUnknownCallback
  ledger-core/cmd/protoc-gen-ins/plugins/gogobased/unmarshal.go
  ledger-core/rms/proto_catalog.pb.go
  ledger-core/rms/proto_common.pb.go
  ledger-core/rms/proto_legacy.pb.go
  ledger-core/rms/proto_legacy_packet.pb.go
  ledger-core/rms/proto_legacy_profile.pb.go
  ledger-core/rms/proto_records.pb.go
  ledger-core/rms/proto_vnlmn.pb.go
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/rmsbox/any_record_lazy.go
  ledger-core/rms/rmsbox/any_record_lazy_body.pb.go
  ledger-core/rms/rmsreg/registry.go
  ledger-core/rms/rmsreg/serializable.go
Labels: automerge, autoupdate

#839 NOISSUE: Remove deprecated GetHash
  ledger-core/reference/decoder_test.go
  ledger-core/reference/local.go
  ledger-core/virtual/integration/utils/server.go
Labels: automerge, autoupdate

#842 NOISSUE: delay test fails
  ledger-core/virtual/object/object_test.go
Labels: automerge, autoupdate

#843 NOISSUE: fix benchmarks with manual pulsar
  ledger-core/application/testutils/launchnet/cloud.go
Labels: automerge, autoupdate

#848 PLAT-257: update reporter version
  .github/workflows/consensus-checks.yaml
Labels: automerge, autoupdate, hacktoberfest-accepted

#845 PLAT-827: Implement parallelism test
  ledger-core/network/nds/msgdelivery/controller_bench_test.go
  ledger-core/network/nds/msgdelivery/controller_parallelism_test.go
  ledger-core/network/nds/msgdelivery/protocol_test.go
  ledger-core/network/nds/msgdelivery/uniproto_utils_test.go
  ledger-core/network/nds/uniproto/l2/uniserver/server.go
Labels: autoupdate

#849 NOISSUE: fix benches that were broken by changes in object descriptor
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#850 NOISSUE: Reference field in rms.ObjectState should global ref
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/handlers/vstatereport_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/constructor_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/utils/vstatereport.go
  ledger-core/virtual/integration/vdelegated_test.go
  ledger-core/virtual/integration/vstatereport_test.go
  ledger-core/virtual/object/object.go
  ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go
Labels: automerge, autoupdate

#851 NOISSUE: state report builder for tests
  ledger-core/virtual/integration/benchs/basic_test.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/deactivate_test.go
  ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
  ledger-core/virtual/integration/deduplication_test.go
  ledger-core/virtual/integration/delegationtoken_test.go
  ledger-core/virtual/integration/memory_request_test.go
  ledger-core/virtual/integration/method_pulse_change_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/statereport_test.go
  ledger-core/virtual/integration/staterequest_test.go
  ledger-core/virtual/integration/testwallet/pulse_change_test.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/utils/statereportbuilder.go
  ledger-core/virtual/integration/utils/vstatereport.go
  ledger-core/virtual/integration/vdelegated_test.go
  ledger-core/virtual/integration/vstatereport_test.go
Labels: automerge, autoupdate

#852 HOTFIX: fix broken BenchmarkTestAPIGetBalance
  ledger-core/virtual/integration/benchs/basic_test.go
Labels: automerge, autoupdate

#853 NOISSUE: rework CachedMemory request/response
  ledger-core/rms/proto_vnvn.pb.go
  ledger-core/rms/proto_vnvn.proto
  ledger-core/rms/proto_vnvn_validation_vcachedmemoryrequest.go
  ledger-core/rms/proto_vnvn_validation_vcachedmemoryresponse.go
  ledger-core/virtual/handlers/vcachedmemoryrequest.go
  ledger-core/virtual/integration/memory_request_test.go
Labels: automerge, autoupdate

#856 HOTFIX: another broken benchmark
  ledger-core/runner/bench_test.go
Labels: automerge, autoupdate

#846 NOISSUE: msgdelivery postponed fix
  ledger-core/network/nds/msgdelivery/controller.go
  ledger-core/network/nds/msgdelivery/ctl_retry_msg.go
  ledger-core/network/nds/msgdelivery/ctl_retry_msg_worker.go
  ledger-core/network/nds/msgdelivery/ctl_retry_state.go
  ledger-core/network/nds/msgdelivery/ctl_retry_state_worker.go
  ledger-core/network/nds/msgdelivery/retries/staged.go
  ledger-core/network/nds/msgdelivery/retries/staged_test.go
  ledger-core/network/nds/uniproto/l2/uniserver/server.go
  ledger-core/network/nds/uniproto/l2/uniserver/server_test_conflict.go
  ledger-core/network/nds/uniproto/l2/uniserver/server_test_conflict_test.go
  ledger-core/vanilla/synckit/semaphore.go
Labels: automerge, autoupdate

#854 NOISSUE: fix too many open files in pulsewatcher
  ledger-core/pulsewatcher/runner.go
Labels: automerge, autoupdate

#855 NOISSUE: typed mock for reference builder
  ledger-core/tools.go
  ledger-core/virtual/integration/mock/referencebuilder/checker/common.go
  ledger-core/virtual/integration/mock/referencebuilder/checker/typed.go
  ledger-core/virtual/integration/mock/referencebuilder/cmd/insolar-mockgenerator-referencebuilder/main.go
  ledger-core/virtual/integration/mock/referencebuilder/cmd/insolar-mockgenerator-referencebuilder/template.go
  ledger-core/virtual/integration/mock/referencebuilder/referencebuilder.go
Labels: automerge, autoupdate

#857 NOISSUE: fix type conversion
  ledger-core/virtual/integration/mock/referencebuilder/checker/typed.go
  ledger-core/virtual/integration/mock/referencebuilder/cmd/insolar-mockgenerator-referencebuilder/template.go
Labels: automerge, autoupdate

#859 NOISSUE: filter records in referencebuilder mock generator
  ledger-core/virtual/integration/mock/referencebuilder/cmd/insolar-mockgenerator-referencebuilder/main.go
Labels: automerge, autoupdate

#862 NOISSUE: added benchmark checks on PR
  .github/workflows/linux-checks.yaml
  ledger-core/Makefile.testing
Labels: automerge, autoupdate

#869 NOISSUE: Attempt to fix TestManyServersEcho
  .github/workflows/long-integration.yaml
  ledger-core/network/nds/msgdelivery/controller_test.go
Labels: automerge, autoupdate

#812 NOISSUE: Reference tools
  ledger-core/ledger/jet/jet_id.go
  ledger-core/ledger/reftypes/common.go
  ledger-core/ledger/reftypes/type.go
  ledger-core/ledger/reftypes/type_api.go
  ledger-core/ledger/reftypes/type_api_test.go
  ledger-core/ledger/reftypes/type_builtin.go
  ledger-core/ledger/reftypes/type_builtin_test.go
  ledger-core/ledger/reftypes/type_jet.go
  ledger-core/ledger/reftypes/type_jet_payload.go
  ledger-core/ledger/reftypes/type_jet_payload_test.go
  ledger-core/ledger/reftypes/type_jet_record.go
  ledger-core/ledger/reftypes/type_jet_record_test.go
  ledger-core/ledger/reftypes/type_jet_test.go
  ledger-core/ledger/reftypes/type_node.go
  ledger-core/ledger/reftypes/type_node_test.go
  ledger-core/ledger/reftypes/type_object.go
  ledger-core/ledger/reftypes/type_object_test.go
  ledger-core/ledger/reftypes/types.go
  ledger-core/pulse/pulse_number.go
  ledger-core/pulse/special_pulse_numbers.go
Labels: autoupdate

#873 NOISSUE: stop scheduled consensus checks
  .github/workflows/consensus-checks.yaml
Labels: automerge, autoupdate

#863 PLAT-850: isolate message sending from record building for SubSMRegister
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/server/internal/virtual/app_factory.go
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute.plantuml
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/handlers/lregisterresponse.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/utils/vcallrequest.go
  ledger-core/virtual/lmn/register.go
  ledger-core/virtual/testutils/utils.go
  ledger-core/virtual/testutils/virtualdebugger/stepmachine.go
  ledger-core/virtual/virtual.go
  ledger-core/virtual/vnlmn/interceptor.go
  ledger-core/virtual/vnlmn/recordreferencebuilder.go
  ledger-core/virtual/vnlmn/register.go
  ledger-core/virtual/vnlmn/register.plantuml
  ledger-core/virtual/vnlmn/register_context.go
  ledger-core/virtual/vnlmn/register_send.go
  ledger-core/virtual/vnlmn/register_send.plantuml
  ledger-core/virtual/vnlmn/register_waitsafe.go
  ledger-core/virtual/vnlmn/register_waitsafe.plantuml
  ledger-core/virtual/vnlmn/resultawaitkey.go
  ledger-core/virtual/vnlmn/saferesponsecounter.go
Labels: automerge, autoupdate

#875 PLAT-629: replace reference builder with rms lazy references
  ledger-core/application/testwalletapi/statemachine/statemachine.go
  ledger-core/application/testwalletapi/statemachine/statemachine_test.go
  ledger-core/rms/rmsbox/provider_ref.go
  ledger-core/server/internal/virtual/app_factory.go
  ledger-core/virtual/execute/delegatedtokenrequest_test.go
  ledger-core/virtual/execute/execute.go
  ledger-core/virtual/execute/execute_semiintegration_test.go
  ledger-core/virtual/execute/execute_test.go
  ledger-core/virtual/execute/migration_test.go
  ledger-core/virtual/integration/utils/server.go
  ledger-core/virtual/integration/utils/vcallrequest.go
  ledger-core/virtual/testutils/utils.go
  ledger-core/virtual/testutils/virtualdebugger/stepmachine.go
  ledger-core/virtual/virtual.go
  ledger-core/virtual/vnlmn/register.go
  ledger-core/virtual/vnlmn/register_context.go
  ledger-core/virtual/vnlmn/register_send.go
  ledger-core/virtual/vnlmn/register_waitsafe.go
Labels: automerge

#840 NOISSUE: ledger drop finalize rev2
  ledger-core/ledger/api_directory.go
  ledger-core/ledger/server/buildersvc/bundle/api_reader.go
  ledger-core/ledger/server/buildersvc/ctlsection/assist.go
  ledger-core/ledger/server/buildersvc/ctlsection/filament_list.go
  ledger-core/ledger/server/buildersvc/ctlsection/ordinal_list.go
  ledger-core/ledger/server/buildersvc/ctlsection/plash_summary.go
  ledger-core/ledger/server/buildersvc/ctlsection/ref_spn.go
  ledger-core/ledger/server/buildersvc/entry_bundle.go
  ledger-core/ledger/server/buildersvc/memstor/finder_ordinal_index.go
  ledger-core/ledger/server/buildersvc/memstor/memory_reader.go
  ledger-core/ledger/server/buildersvc/memstor/memory_reader_map.go
  ledger-core/ledger/server/buildersvc/memstor/memory_writer.go
  ledger-core/ledger/server/buildersvc/plash_assist.go
  ledger-core/ledger/server/dataextractor/api_iterator.go
  ledger-core/ledger/server/dataextractor/api_limiter.go
  ledger-core/ledger/server/dataextractor/api_output.go
  ledger-core/ledger/server/dataextractor/api_selector.go
  ledger-core/ledger/server/dataextractor/filament_selector.puml
  ledger-core/ledger/server/dataextractor/limiter.go
  ledger-core/ledger/server/dataextractor/limiter_everything.go
  ledger-core/ledger/server/dataextractor/reader.go
  ledger-core/ledger/server/datareader/api_record_extractor.go
  ledger-core/ledger/server/datareader/extractor_whole.go
  ledger-core/ledger/server/datareader/smreader.go
  ledger-core/ledger/server/datareader/smreader_next.go
  ledger-core/ledger/server/datareader/smreader_prev.go
  ledger-core/ledger/server/datawriter/smdirtyreader.go
  ledger-core/ledger/server/datawriter/smdirtyreader_iterator.go
  ledger-core/ledger/server/datawriter/smline_data.go
  ledger-core/ledger/server/inspectsvc/service.go
  ledger-core/ledger/server/lineage/line_staged.go
  ledger-core/ledger/server/lineage/record.go
  ledger-core/ledger/server/lmnapp/lmntestapp/record_builder.go
  ledger-core/ledger/server/lmnapp/tests/lifeline_test.go
  ledger-core/ledger/server/lmnapp/tests/storage_test.go
  ledger-core/ledger/server/readersvc/readbundle/api_reader.go
  ledger-core/ledger/server/requests/response_output.go
  ledger-core/ledger/server/requests/smread.go
  ledger-core/rms/proto_catalog.go
  ledger-core/rms/proto_catalog.pb.go
  ledger-core/rms/proto_catalog.proto
  ledger-core/rms/proto_rec_ctl.pb.go
  ledger-core/rms/proto_rec_ctl.proto
  ledger-core/rms/proto_vnlmn.pb.go
  ledger-core/rms/proto_vnlmn.proto
  ledger-core/rms/rmsbox/reference.go
  ledger-core/vanilla/longbits/fixed_size.go
Labels: WIP, autoupdate, ledger

#877 PLAT-858: Service network benchmark
  ledger-core/network/hostnetwork/hostnetwork.go
  ledger-core/network/servicenetwork/servicenetwork_benchmark_test.go
Labels: automerge, autoupdate

#876 PLAT-823: VN-LMN message checker
  ledger-core/testutils/recordchecker/checker.go
  ledger-core/testutils/recordchecker/checker_test.go
  ledger-core/testutils/recordchecker/helpers.go
  ledger-core/virtual/integration/constructor_test.go
  ledger-core/virtual/integration/constructor_with_lmn_test.go
  ledger-core/virtual/integration/method_test.go
  ledger-core/virtual/integration/utils/vcallrequest.go
  ledger-core/virtual/vnlmn/register.go
Labels: automerge, autoupdate

#878 PLAT-782: Controllable MNP
  ledger-core/application/benchs/benchrunner_test.go
  ledger-core/application/benchs/cloud_test.go
  ledger-core/application/functest/main_func_cloud_test.go
  ledger-core/application/functest/main_func_cloud_with_consensus_test.go
  ledger-core/application/functest/test_utils.go
  ledger-core/application/jepsen_tests/basic_test.go
  ledger-core/application/testutils/apiutils.go
  ledger-core/application/testutils/launchnet/cloud.go
  ledger-core/application/testutils/launchnet/cloud_test.go
  ledger-core/application/testutils/launchnet/cloud_with_consensus.go
  ledger-core/application/testutils/launchnet/helper.go
  ledger-core/application/testutils/launchnet/launchnet.go
  ledger-core/cmd/insolard/cloud.go
  ledger-core/instrumentation/insapp/api_config.go
  ledger-core/instrumentation/insapp/api_multi.go
  ledger-core/instrumentation/insapp/init_components.go
  ledger-core/instrumentation/insapp/server.go
  ledger-core/instrumentation/insapp/server_lifecycle_mono.go
  ledger-core/instrumentation/insapp/server_lifecycle_multi.go
  ledger-core/instrumentation/insapp/server_multi.go
  ledger-core/server/internal/headless/app_factory_test.go
  ledger-core/server/internal/virtual/app_factory_test.go
  ledger-core/server/server.go
  ledger-core/testutils/cloud/configuration.go
  ledger-core/testutils/cloud/controller.go
  ledger-core/testutils/cloud/controller_test.go
  ledger-core/testutils/cloud/network.go
  ledger-core/testutils/cloud/pulsar.go
  ledger-core/testutils/cloud/setup.go
Labels: automerge
